### ISSUE TITLE
Setup file request

### ISSUE THREAD

**Issue by ncyxie** [XesignSoftware/WebcamViewerUWP#1]
I'd want to test this application by myself, but the only way to do it is to compile it. I don't use any C# compilers and it would be pointless to install one just for this project tryout. **The setup file would be handy for me and possibly for others as well to use your project as an application and not as a code source.**

**Comment by xezrunner** [comment]
Thanks for the interest!
For the moment, this application is not in a state of development that would necessitate a package file to be uploaded.
Once bare minimum levels of functionality are reached, I will provide an `.appxpackage` file through the Releases tab that will let you install the app.
As this is a Windows Universal Platform application, there is no setup required. The app would ideally be distributed through the Microsoft Store or as an `.appxpackage` file.
